### ISSUE TITLE
Make JIRA::REST and Gerrit::REST Optional Dependencies

### ISSUE THREAD

**Issue by sshaw** [gnustavo/Git-Hooks#11]
These modules depend on `REST::Client`, [which depends on `Crypt::SSLeay`](https://metacpan.org/source/MCRAWFOR/REST-Client-272/Makefile.PL#L8). `Crypt::SSLeay` requires compilation -which doesn't always go well. Failures can discourage non-Perl devs from using (or being sold on) a good Perl-based took like `Git::Hooks`.

`JIRA::REST` and `Gerrit::REST` should be [like `CheckLog` and `Text::SpellChecker`](https://github.com/gnustavo/Git-Hooks/tree/next/lib/Git/Hooks/CheckLog.pm#L50). Actually, it looks like this approach was partially attempted with `Gerrit::REST` [here](https://github.com/gnustavo/Git-Hooks/tree/next/lib/Git/Hooks.pm#L382).

**Comment by sshaw** [comment]
`REST::Client` also depends on `XML::LibXML`.

**Comment by sshaw** [comment]
On OS X `Text::SpellChecker` fails too (no `aspell`, though I thought `Text::SpellChecker` wasn't picky about this, anyways...). At one point you did [remove the explicitly dependency on `Text::SpellChecker` and `JIRA::REST`](https://github.com/gnustavo/Git-Hooks/commit/a16860f), only to [put them back](https://github.com/gnustavo/Git-Hooks/commit/757233c) shortly thereafter. (There are still some remnants of this being optional [here](https://github.com/gnustavo/Git-Hooks/tree/next/lib/Git/Hooks/CheckLog.pm#L50).)

Of course I can resolve these quite easily but, as I mentioned earlier, my concern is making this easy for devs that aren't familiar with Perl (like those on my development team :smile_cat:). The easier it is to make this work with `sudo cpan Git::Hooks` the better. Don't you agree? 

Once the install(s) is done all config is `git` based so...  

Let me know what I can do to help!

**Comment by mikkoi** [comment]
I have also struggled with the installation, especially when other developers are involved. My solution is here: https://github.com/mikkoi/.git-repo-admin
The idea is that every Git repo has a directory called ".git-repo-admin", and there is a script called "initialize-hooks.sh". When developer activates the hooks, the system Perl installation is not touched. No sudo required, instead local installation with plenv and Carton. The (local) hooks even set themselves up in a way that they are automatically updated when developer pulls from repo.

**Comment by sshaw** [comment]
> I have also struggled with the installation, especially when other developers are involved. 
> My solution is here: https://github.com/mikkoi/.git-repo-admin

@mikkoi the problem I have with that is that the room for installation/compilation errors is greatly expanded from `Git::Hooks` to a full-fledged Perl install + `Carton`. OS X already comes with perl, for my team it's preferable to piggy back on that.

**Comment by mikkoi** [comment]
@sshaw Our development environments are Debian and Ubuntu distributions. They also come with Perl. But with plenv (actually, plenv via anyenv: https://github.com/riywo/anyenv) .git-repo-admin starts with a fresh Perl installation and all packages are installed into it, instead of the system Perl (which could be any version). That way the Git::Hooks installation remains completely isolated from the rest of the system.
However, we have not tested it with OS X, so I can't say if it would work reliably. Sorry.

**Comment by gnustavo** [comment]
Good points! I intend to get to it in a few days. Thanks!

2015-02-26 4:36 GMT-03:00 Mikko Koivunalho notifications@github.com:

> @sshaw https://github.com/sshaw Our development environments are Debian
> and Ubuntu distributions. They also come with Perl. But with plenv
> (actually, plenv via anyenv: https://github.com/riywo/anyenv)
> .git-repo-admin starts with a fresh Perl installation and all packages are
> installed into it, instead of the system Perl (which could be any version).
> That way the Git::Hooks installation remains completely isolated from the
> rest of the system.
> However, we have not tested it with OS X, so I can't say if it would work
> reliably. Sorry.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gnustavo/Git-Hooks/issues/11#issuecomment-76134383.

## 

Gustavo.

**Comment by gnustavo** [comment]
I'll wait to see if [this ticket](https://rt.cpan.org/Ticket/Display.html?id=102340) is resolved in the REST::Client queue because if it is it'll solve the problem for every module that depends on it.

**Comment by gnustavo** [comment]
I've just released v1.6.10 which makes JIRA::REST a recommendation, because it's only needed by the CheckJira plugin. I'm thinking about moving this plugin to it's own distribution so that it can require JIRA::REST.

Anyway, this doesn't solve this issue because we still require Gerrit::REST. But since it's required by core Git::Hooks and not merely by a plugin I can't easily change it. I'm going to wait more to see if REST::Client solve it's issues so that this one is solved indirectly.

**Comment by sshaw** [comment]
> ... this doesn't solve this issue because we still require Gerrit::REST. 
> But since it's required by core Git::Hooks and not merely by a plugin I can't easily change it

May be core, but not sure why. If people aren't using Gerrit no need to force them to install it, particularly with `Crypt::SSLeay`. 

Maybe just change [this](https://github.com/gnustavo/Git-Hooks/blob/next/lib/Git/Hooks.pm#L382) to [something like this](https://github.com/gnustavo/Git-Hooks/blob/next/lib/Git/Hooks/CheckLog.pm#L51). Or [this](https://github.com/gnustavo/Git-Hooks/blob/next/lib/Git/Hooks.pm#L516-524) to:

``` perl
if( !eval {require Gerrit::REST} ) {
  warn 'no Gerrit::REST';
}
else {
   $prepare_hooks{'patchset-created'} = \&_prepare_gerrit_patchset;
   $prepare_hooks{'draft-published'}  = \&_prepare_gerrit_patchset;
   # ...
}
```

>  I'm going to wait more to see if REST::Client solve it's issues so that this one is solved indirectly.

:pray:

**Comment by gnustavo** [comment]
I thought better and saw that you're right @sshaw. There's no need to make Gerrit::REST a requirement.
