### ISSUE TITLE
Text::SpellChecker has made its way to Makefile.PL's PREREQ_PM list

### ISSUE THREAD

**Issue by mikkoi** [gnustavo/Git-Hooks#14]
... and because of the installation problems (the file aspell.h is missing from e.g. Aspell's Debian distribution archive), I cannot install Git::Hooks.

I noticed that you had already removed Text::SpellChecker from dist.ini's recommended modules list. It seems to be haunting.

Because of the problems in Text::SpellChecker, I think we need some other way to integrate the support for it. Or it there other spell checker support Perl modules?
## 

Mikko

**Comment by gnustavo** [comment]
Hi Mikko. I've just released v1.6.10 which should make Text::SpellChecker a recommendation again. Please check it out and tell me if it's ok.

**Comment by mikkoi** [comment]
Thanks, Gustavo.
Installation works without problem again.
