### ISSUE TITLE
Admin Rights Are Too Wide

### ISSUE THREAD

**Issue by mikkoi** [gnustavo/Git-Hooks#23]
We need a way to limit admin access.
For instance, in our case, admin group members need to be able to create and remove branches (hook _CheckAcls_), but not be able to make mistakes in commit messages (_CheckLog_) or commit without a signature (_CheckCommit_).

Maybe every hook could have its own config item _admin_ specifying which groups have admin access in it.

**Comment by gnustavo** [comment]
Can't you accomplish this by defining another group instead of "admin" and configuring it on the CheckAcls?

**Comment by mikkoi** [comment]
Trying. Will report. Thank you for the suggestion.

**Comment by mikkoi** [comment]
It worked perfectly.

extract from our config:
    groups = GroupAdmins = me other
    groups = GroupReleaseManagers = third.person
[githooks "checkacls"]
    acl = @GroupAdmins CRUD ^refs/heads/                        # Only admins can do everything to every branch.
    acl = ^.+ U ^refs/heads/master$                             # All users can update the master branch.
    acl = ^.+ CRUD ^refs/heads/{USER}/                          # Every user can manage branches in their own namespace.
    acl = ^.+ RU ^refs/heads/common/                            # All users can update common branches.
    acl = @GroupReleaseManagers CRUD ^refs/heads/release-       # Release branches...
    acl = @GroupReleaseManagers CRUD ^refs/tags/                # Release tags...
    acl = ^.+ RU ^refs/heads/release-                           # All users can rewind and update the release branches.

**Comment by gnustavo** [comment]
Good to know that!

Just one tip to simplify your config: you can replace the `^.+` regexes by a simple `.`, because both match anything.
