### ISSUE TITLE
When pushing a new branch the CheckJira hook can deny this because no open issue found

### ISSUE THREAD

**Issue by ate** [gnustavo/Git-Hooks#24]
This was a surprise to us, and we haven't figured out yet how it actually works, or works incorrectly.

But when a user pushes a new remote branch, it seems the CheckJira hook tries to validate if there is any commit reachable from NEWCOMMIT ref (the branch HEAD, which is at this time also the baseline branch HEAD from which the new branch is created), which has an open JIRA ticket.
If none is found, then the CheckJira hook will deny the pushing of the branch.

However, pushing a new remote branch really is not, should not be, related to any of the commits in the baseline branch from which the branch is created.
So checking for a commit with an open JIRA ticket when pushing a new branch seems wrong.

Is the above correct or did we configure something wrong?

Thanks, Ate

**Comment by boudekerk** [comment]
It seems that when pushing a new branch, even if it includes other commits, the oldsha is 0000000000000000000000000000000000000000, and all commits are checked, instead of only the new ones. In our case this triggers the CheckJira hook against (all) old commits. If I'm not mistaken, if the oldsha is the above, you'd want to evaluate only commits "that will be reachable given the proposed creation, that are not currently reachable at all." (git rev-list $newsha --not --all).

See: http://stackoverflow.com/questions/22546393/can-git-pre-receive-hooks-evaulate-the-incoming-commit

Are we correct in thinking this is a bug?

**Comment by schans** [comment]
Hi, @gnustavo ,

I have created a fix that at least for us seems to solve the problem. Could you please review and give some feedback. Not sure if there is a nicer way to achieve the same.

Thanks!
Bart

**Comment by gnustavo** [comment]
Hi there!

Yes, you're right. CheckJira should check only new commits brought on by the new branch being pushed, and not re-check commits already reachable by other existing branches.

But as it is CheckJira should do this right. The specific code is in the Git::More::get_commits routine, which groks all the commits from a range. For new branches, the range starting point is the null-commit (40 x '0'). When I implemented this I didn't know about the --not option to rev-list and did it in a more explicit way by using the git-for-each-ref command to get all the branch names and prefixing them with carets. This isn't exactly the same as "git rev-list --not --all". It's like "git rev-list --not --branches", though, which should be enough I think.

I'm not excluding the possibility of a bug having sneaked in that code. However, I did a simple test and it worked for me. I created two git repositories A and B and started creating commits in A and pushing them to B. In B I set up the following pre-receive hook which simply prints a line for each reference being received (from A) along side the list of commits being brought by it, using the same code that CheckJira currently uses to get the affected commit list. The hook fails everytime just to make it easier to repeat the experiments:

``` perl
#!/usr/bin/env perl

use Git::Hooks;

PRE_RECEIVE {
    my ($git) = @_;

    foreach my $ref ($git->get_affected_refs()) {
        my @commits = $git->get_affected_ref_commits($ref);
        print "$ref: ", join(', ', map {$_->{commit}} @commits), "\n";
    }

    $git->error(PREFIX => "THOU SHALL NOT PASS!");
};

run_hook($0, @ARGV);
```

I created a master branch in A with a few commits and pushed them to B before enabling the hook.

Then I created another branch and did two commits on it.

Then I pushed it and the hook showed me just the two commits in the new branch. No commits already pushed to master was shown.

Perhaps your case is different in a way that triggers a bug. Could you try to reproduce it in a small scale using the method above to let me know exactly what could be wrong? If you can't try to explain to me how I can reproduce the error.

Thanks!

**Comment by boudekerk** [comment]
Hi @gnustavo,

I can reproduce it like so:

```
git init git-hooks-issue-24-remote
cd git-hooks-issue-24-remote
git checkout -b new-branch # Otherwise git complains about pushing to a checked out branch
cd ..
git clone file:///path/to/git-hooks-issue-24-remote git-hooks-issue-24-local
cd git-hooks-issue-24-local
echo ${RANDOM} > README; git add README; git commit -m"Testing" README
git push
echo ${RANDOM} > README; git commit -m"Testing" README
git push
git checkout -b test-branch
ln -sf /data/git/bin/githooks.pl /path/to/git-hooks-issue-5-remote/.git/hooks/pre-receive
git push -u origin test-branch
```

The output is:

```
remote: [PREFIX] THOU SHALL NOT PASS!
remote: 
remote: [Git::Hooks::CheckJira] commit d21fd82c must cite a JIRA in its message
remote: 
remote: [Git::Hooks::CheckJira] commit 93594b15 must cite a JIRA in its message
remote: 
remote: refs/heads/test-branch: d21fd82cc83d3888f2e58fbc54ec809a8d299a3b, 93594b15e3f975c65f03d1667e08f9275b1ad386
```

With Bart's patch the push succeeds.

**Comment by gnustavo** [comment]
Hi @boudekerk,

Thanks to your description I was able to figure out the bug. It happens when you push a new branch in which you haven't done any commits yet.

I just commited a fix in 023b463 and I'm going to cut a new release. Please, check it out and tell me if it works for you, ok?

Thanks!

**Comment by gnustavo** [comment]
Oops, I just found a typo in my fix and amended the fix commit which is now 01d35db. ;-)

**Comment by boudekerk** [comment]
Hi @gnustavo,

I just did a couple of test, and everything now seems to work as expected. Thank you!

Kind regards,
Bartosz

P.s. Can we expect a new release soon? If not we'll just patch More.pm by hand for now.

**Comment by boudekerk** [comment]
Sorry, I missed that there already was a 1.12.2
