### ISSUE TITLE
When pushing a merge, older commits on the branch being merged are checked.

### ISSUE THREAD

**Issue by boudekerk** [gnustavo/Git-Hooks#26]
Hi @gnustavo,

we have another issue which seems related to issue 24. This time we're merging, please see the following reproduction path:

```
CWD=$(pwd)
git init git-hooks-issue-remote
cd git-hooks-issue-remote
git checkout -b new-branch #Otherwise we can't push to this repo's master
cd ..
git clone file://"${CWD}"/git-hooks-issue-remote git-hooks-issue-local
cd git-hooks-issue-local
echo ${RANDOM} > README; git add README; git commit -m"Testing 1" README
git push
git checkout -b test-branch
git push -u origin test-branch
echo ${RANDOM} > README.test-branch; git add README.test-branch; git commit -m"Testing b 1" README.test-branch
git push
git checkout master
echo ${RANDOM} > README.master; git add README.master; git commit -m"Testing m 1" README.master
git push
git checkout test-branch
ln -sf /data/git/bin/githooks.pl ${CWD}/git-hooks-issue-remote/.git/hooks/pre-receive
git merge -m"<VALID_JIRA_ISSUE>: Test merge" master
git push
```

I _think_ this could be solved using the same rev-list command as in issue 24. Could you please have a look?

Thank you,
Bartosz

**Comment by gnustavo** [comment]
Yeah... I think you're right. Merge commits along the way from $old_commit to $new_commit make "git rev-list $new_commit ^$old_commit" return the commits from the other side of the merge too, which we don't want to see.

I think I should always use "git rev-list --not --all" and also exclude $old_commit if it's not the NULL commit (for new branches).

I'm going to make a patch next.

**Comment by gnustavo** [comment]
I've just released version 1.12.3 which hopefully fixes this. It should appear shortly on CPAN. Please, check it out and tell me how it goes.

**Comment by boudekerk** [comment]
I will. Thank you.

**Comment by boudekerk** [comment]
It seems to work great with that fix Thank you!

**Comment by gnustavo** [comment]
Thank you!
