### ISSUE TITLE
Token check only use working dir file state

### ISSUE THREAD

**Issue by stacyharper** [gnustavo/Git-Hooks#48]
Hello guys,
After some tests, it's clear that file token check only read working dir files.

- Add "todo" in a file
- Git add the file
- Git commit => token check deny the commit (cool !)
- Remove "todo" from the file
- DO NOT GIT ADD THE FILE
- Git commit => "token check DO NOT deny the commit (Whoo !)

I was affraid that CheckFile only read the working dir files, but, reading the code teach me that check_command use tmp files created from the git indexed files.

Why deny_token use working dir files and not git indexed files ?

TY dudes !

**Comment by gnustavo** [comment]
Hi Eddie. Good catch! Thanks for the report.

I just fixed it on commit 29ef0c7.

I'll cut a new release soon.
