### ISSUE TITLE
Error message prefix

### ISSUE THREAD

**Issue by boudekerk** [gnustavo/Git-Hooks#62]
It would be nice if we could prefix the actual error message. GitLab requires this to show the message in the UI.
The error-header doesn't work for this as it's not on the same line.

https://docs.gitlab.com/ee/administration/server_hooks.html#custom-error-messages

**Comment by gnustavo** [comment]
Good idea! I'll think about it.

**Comment by gnustavo** [comment]
I just released v2.12.0 with a new configuration option (githooks.error-prefix) which should help with this.

Please, try it out and comment.

**Comment by boudekerk** [comment]
Works like a charm. Thanks!
