### ISSUE TITLE
Put Functions in test-functions.pl into Test::Git::Hooks or Git::Hooks::Test

### ISSUE THREAD

**Issue by sshaw** [gnustavo/Git-Hooks#9]
I wanted to test the [hook I wrote](https://github.com/sshaw/Git-Hooks-RubyNoDebugger) so I had a peek at some of your tests. [test-functions.pl](https://github.com/gnustavo/Git-Hooks/blob/v1.6.9/t/test-functions.pl) contains a lot of functions that could be helpful to `Git::Hooks` plugin authors. You should make it a module.

**Comment by gnustavo** [comment]
2015-02-22 19:20 GMT-03:00 Skye Shaw notifications@github.com:

> I wanted to test the hook I wrote
> https://github.com/sshaw/Git-Hooks-RubyNoDebugger so I had a peek at
> some of your tests. test-functions.pl
> https://github.com/gnustavo/Git-Hooks/blob/v1.6.9/t/test-functions.pl
> contains a lot of functions that could be helpful to Git::Hooks plugin
> authors. You should make it a module.
> 
> Good idea. But it will require some effort that I'm not able to do shortly.
> I'll make a note in the TODO file. But I'm open to pull requests also. :-)

Looking at your plugin it seems like an easily "generalizable" idea. I
mean, why have a plugin to look for a specific pattern if you can have one
to look after any pattern? I'm thinking about something like
Git::Hooks::DenyPattern that you could pass patterns to it via
configuration like this:

[githooks "denypattern"]
  deny = [MESSAGE] /REGEXP/
  deny = [MESSAGE] /REGEXP/

MESSAGE would be optional: a specific message telling the user what has
been matched.

What do you think?

## 

Gustavo.

**Comment by sshaw** [comment]
> Looking at your plugin it seems like an easily "generalizable" idea.
>  I mean, why have a plugin to look for a specific pattern if you can 
> have one to look after any pattern? 

I agree that it would be good to have a generic plugin `DenyPattern`. 

In the case of `RubyNoDebugger` this is something so common that it's better to prepackage it.

**Comment by sshaw** [comment]
> [githooks "denypattern"]
>  deny = [MESSAGE] /REGEXP/
>  deny = [MESSAGE] /REGEXP/

You should also add file extension. 

Also, does `Git::Hooks` provide an easy way to get a diff?

**Comment by gnustavo** [comment]
@sshaw I just merged #35 in which @majlo implemented what you suggested here.

**Comment by sshaw** [comment]
Ótimo!
